have_total = 0
print("レア10:10　レア9:9　レア8:8")
goal_rarity = input("目標レアリティ:")
goal_rarity = int(goal_rarity)
goal_count = 3 ** (goal_rarity - 1)
print("今持ってる装備")
have_rarity = input("レア9:")
have_total += 3 ** 8 * int(have_rarity)
have_rarity = input("レア8:")
have_total += 3 ** 7 * int(have_rarity)
have_rarity = input("レア7:")
have_total += 3 ** 6 * int(have_rarity)
have_rarity = input("レア6:")
have_total += 3 ** 5 * int(have_rarity)
have_rarity = input("レア5:")
have_total += 3 ** 4 * int(have_rarity)
have_rarity = input("レア4:")
have_total += 3 ** 3 * int(have_rarity)
have_rarity = input("レア3:")
have_total += 3 ** 2 * int(have_rarity)
have_rarity = input("レア2:")
have_total += 3 * int(have_rarity)
have_rarity = input("レア1:")
have_total += int(have_rarity)
print("持ってる数" + str(have_total))
print("レア" + str(goal_rarity) + "の必要数" + str(goal_count))
rest = goal_count - have_total
if rest <= 0:
    print("もう作れる") 
else:
    print("あと白換算で" + str(rest))